### ISSUE TITLE
Nodejs instrumentation - Propagator "xray" requested through environment variable is unavailable.

### ISSUE THREAD

**Issue by ademar-prothon** [open-telemetry/opentelemetry-operator#1869]
We are unable to use the xray propagator on an auto-instrumented nodejs app.
Env : k8s on eks v 1.26.4

Instrumentation : 
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: exchange-platform
  namespace: default
spec:
  exporter:
    endpoint: http://xray-collector-collector.default.svc.cluster.local:4318
  propagators:
    - xray
  sampler:
    type: always_on
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://xray-collector-collector.default.svc.cluster.local:4317
      - name: OTEL_LOG_LEVEL
        value: info
```
Error message : 
`Propagator "xray" requested through environment variable is unavailable.`

Any ideas ? Thanks !

**Comment by TylerHelmuth** [comment]
@ademar-prothon thanks for bring this to our attention. For this to work we need to modify [this file](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/src/autoinstrumentation.ts) and the package.json to include the xray propagator.  Is this something you'd like to work on?

**Comment by fracampit** [comment]
just hit the same problem. Is there any that can be done at our end, or is xray currently unavailable for NodeJs instrumentation?

**Comment by fracampit** [comment]
> @fracampit We need the NodeJS sdk updated: [#1872 (comment)](https://github.com/open-telemetry/opentelemetry-operator/pull/1872#discussion_r1253770528)

Thanks for the update. I'll keep an eye on this space then :)

**Comment by adityamehra** [comment]
Hello @TylerHelmuth Was this issue fixed by https://github.com/open-telemetry/opentelemetry-js/pull/4554?

**Comment by fracampit** [comment]
Any updates on this?

**Comment by garysassano** [comment]
I confirm that the error is still present.

![image](https://github.com/user-attachments/assets/6c1ed04e-5054-4997-8720-d22499333427)

![image](https://github.com/user-attachments/assets/b6302863-90c3-4e98-be6a-2433bb7c1e92)

**Comment by jungjinlee-plugo** [comment]
@garysassano 
For reference here, 'Cannot redefine property: handler' error can be solved.
https://github.com/aws-observability/aws-otel-lambda/issues/284#issuecomment-1465465790
